# Generated by Django 3.1.7 on 2021-04-27 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sheets', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomQuery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_month', models.IntegerField()),
                ('end_month', models.IntegerField()),
                ('start_year', models.IntegerField()),
                ('end_year', models.IntegerField()),
                ('tablename', models.CharField(max_length=32)),
                ('district', models.CharField(max_length=32)),
            ],
        ),
    ]
