# Generated by Django 3.1.7 on 2021-04-27 14:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sheets', '0002_customquery'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomQuery',
        ),
    ]
